run:
  tests: true
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 10m

linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - gofumpt
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - exportloopref
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - nolintlint
    - asciicheck
    - exportloopref
    - gomodguard
    - noctx

issues:
  exclude-rules:
    - text: "leading space"
      linters:
        - nolintlint
